import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    'nav.welcome': 'Welcome',
    'nav.quickActions': 'Quick Actions',
    'nav.dashboard': 'Dashboard',
    'nav.appointments': 'Appointments',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.signIn': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.myAppointments': 'My Appointments',
    
    // Home Page
    'home.title': 'Connect with Healthcare',
    'home.subtitle': 'Professionals',
    'home.description': 'The unified platform that brings patients and healthcare providers together. Book appointments, manage services, and provide quality care.',
    'home.getStartedFree': 'Get Started Free',
    'home.findProviders': 'Find Providers',
    'home.whyChoose': 'Why Choose MedConnect?',
    'home.builtFor': 'Built for both patients and healthcare providers',
    
    // Features
    'features.forPatients': 'For Patients',
    'features.forProviders': 'For Providers',
    'features.secureReliable': 'Secure & Reliable',
    'features.freeForever': 'Free forever',
    'features.easyBooking': 'Easy appointment booking',
    'features.providerReviews': 'Provider reviews & ratings',
    'features.professionalDashboard': 'Professional dashboard',
    'features.appointmentManagement': 'Appointment management',
    'features.revenueTracking': 'Revenue tracking',
    'features.hipaaCompliant': 'HIPAA compliant',
    'features.encryption': 'End-to-end encryption',
    'features.support247': '24/7 support',
    
    // Stats
    'stats.activePatients': 'Active Patients',
    'stats.healthcareProviders': 'Healthcare Providers',
    'stats.appointmentsBooked': 'Appointments Booked',
    'stats.averageRating': 'Average Rating',
    
    // CTA
    'cta.transformHealthcare': 'Ready to Transform Healthcare?',
    'cta.joinThousands': 'Join thousands of patients and providers who trust MedConnect for their healthcare needs.',
    'cta.startJourney': 'Start Your Journey',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.book': 'Book',
    'common.view': 'View',
    'common.manage': 'Manage',
    'common.update': 'Update',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.finish': 'Finish',
    'common.select': 'Select',
    'common.choose': 'Choose',
    'common.optional': 'Optional',
    'common.required': 'Required',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.name': 'Name',
    'common.address': 'Address',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.notes': 'Notes',
    'common.type': 'Type',
    'common.status': 'Status',
    'common.actions': 'Actions',
    
    // Providers Page
    'providers.title': 'Find Healthcare Providers',
    'providers.description': 'Book appointments with qualified healthcare professionals',
    'providers.searchPlaceholder': 'Search providers, specialties, or locations...',
    'providers.locationPlaceholder': 'Location',
    'providers.showing': 'Showing',
    'providers.provider': 'provider',
    'providers.providers': 'providers',
    'providers.sortedByDistance': 'sorted by distance',
    'providers.locationBasedResults': 'Location-based results',
    'providers.noProvidersFound': 'No providers found',
    'providers.adjustCriteria': 'Try adjusting your search criteria or expanding your search radius.',
    'providers.expandRadius': 'Expand Search Radius',
    'providers.viewProfile': 'View Profile',
    'providers.bookAppointment': 'Book Appointment',
    'providers.nextAvailable': 'Next available',
    'providers.perConsultation': 'per consultation',
    'providers.services': 'Services',
    'providers.reviews': 'reviews',
    
    // Location
    'location.yourLocation': 'Your Location',
    'location.currentLocation': 'Current location detected',
    'location.gps': '(GPS)',
    'location.useCurrentLocation': 'Use Current Location',
    'location.gettingLocation': 'Getting Location...',
    'location.enterManually': 'Enter Address Manually',
    'location.enterAddress': 'Enter your address or city',
    'location.addressPlaceholder': 'e.g., New York, NY or 123 Main St, City, State',
    'location.setLocation': 'Set Location',
    'location.finding': 'Finding...',
    'location.privacyNote': 'Location data is only used for finding nearby healthcare providers.',
    'location.maxDistance': 'Max Distance',
    'location.miles': 'miles',
    'location.sortBy': 'Sort By',
    'location.distance': 'Distance',
    'location.rating': 'Rating',
    'location.price': 'Price (Low to High)',
    'location.location': 'Location',
    
    // Specialties
    'specialty.allSpecialties': 'All Specialties',
    'specialty.generalMedicine': 'General Medicine',
    'specialty.cardiology': 'Cardiology',
    'specialty.dermatology': 'Dermatology',
    'specialty.pediatrics': 'Pediatrics',
    'specialty.psychology': 'Psychology',
    'specialty.dentistry': 'Dentistry',
    'specialty.physicalTherapy': 'Physical Therapy',
    'specialty.nutrition': 'Nutrition',
    'specialty.other': 'Other',
    
    // Profile
    'profile.title': 'Profile',
    'profile.description': 'Manage your account information and preferences',
    'profile.personalInfo': 'Personal Information',
    'profile.editProfile': 'Edit Profile',
    'profile.fullName': 'Full Name',
    'profile.emailAddress': 'Email Address',
    'profile.phoneNumber': 'Phone Number',
    'profile.location': 'Location',
    'profile.medicalSpecialty': 'Medical Specialty',
    'profile.professionalBio': 'Professional Bio',
    'profile.bioPlaceholder': 'Tell patients about your experience and approach to care...',
    'profile.accountStatus': 'Account Status',
    'profile.accountType': 'Account Type',
    'profile.memberSince': 'Member Since',
    'profile.subscription': 'Subscription',
    'profile.active': 'Active',
    'profile.business': 'Business',
    'profile.personal': 'Personal',
    'profile.quickActions': 'Quick Actions',
    'profile.securitySettings': 'Security Settings',
    'profile.notificationPreferences': 'Notification Preferences',
    'profile.upgradeToBusiness': 'Upgrade to Business',
    'profile.notProvided': 'Not provided',
    'profile.noBio': 'No bio provided',
    
    // Settings
    'settings.title': 'Settings',
    'settings.description': 'Manage your account preferences and security settings',
    'settings.security': 'Security',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.billing': 'Billing',
    'settings.preferences': 'Preferences',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.updatePassword': 'Update Password',
    'settings.twoFactorAuth': 'Two-Factor Authentication',
    'settings.smsAuth': 'SMS Authentication',
    'settings.smsAuthDesc': 'Receive codes via text message',
    'settings.enable2FA': 'Enable 2FA',
    'settings.activeSessions': 'Active Sessions',
    'settings.currentSession': 'Current Session',
    'settings.lastActive': 'Last active',
    'settings.current': 'Current',
    'settings.notificationPrefs': 'Notification Preferences',
    'settings.deliveryMethods': 'Delivery Methods',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive notifications via email',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.smsNotificationsDesc': 'Receive notifications via text message',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotificationsDesc': 'Receive browser push notifications',
    'settings.notificationTypes': 'Notification Types',
    'settings.appointmentUpdates': 'Appointment Updates',
    'settings.appointmentUpdatesDesc': 'Booking confirmations and changes',
    'settings.appointmentReminders': 'Appointment Reminders',
    'settings.appointmentRemindersDesc': 'Reminders before your appointments',
    'settings.marketingComms': 'Marketing Communications',
    'settings.marketingCommsDesc': 'Product updates and promotions',
    'settings.privacySettings': 'Privacy Settings',
    'settings.profileVisibility': 'Profile Visibility',
    'settings.profileVisibilityDesc': 'Control who can see your profile information',
    'settings.public': 'Public',
    'settings.providersOnly': 'Healthcare Providers Only',
    'settings.private': 'Private',
    'settings.dataSharing': 'Data Sharing',
    'settings.dataSharingDesc': 'Manage how your data is shared with healthcare providers',
    'settings.shareHistory': 'Share appointment history with new providers',
    'settings.allowAnalytics': 'Allow anonymous usage analytics',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountDesc': 'Permanently delete your account and all associated data',
    'settings.businessPlan': 'Business Plan',
    'settings.businessPlanDesc': 'Full access to provider features',
    'settings.perMonth': 'per month',
    'settings.manageSubscription': 'Manage Subscription',
    'settings.downloadInvoice': 'Download Invoice',
    'settings.paymentMethod': 'Payment Method',
    'settings.expires': 'Expires',
    'settings.updatePaymentMethod': 'Update Payment Method',
    'settings.languageRegion': 'Language & Region',
    'settings.language': 'Language',
    'settings.timeZone': 'Time Zone',
    'settings.displayPreferences': 'Display Preferences',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.showReminders': 'Show appointment reminders on dashboard',
    
    // Quick Actions
    'quickActions.title': 'Quick Actions',
    'quickActions.providerDescription': 'Manage your practice with these quick actions',
    'quickActions.clientDescription': 'Access common healthcare tasks quickly',
    'quickActions.bookNewAppointment': 'Book New Appointment',
    'quickActions.findProviders': 'Find Providers',
    'quickActions.emergencyContacts': 'Emergency Contacts',
    'quickActions.healthRecords': 'Health Records',
    'quickActions.addAppointment': 'Add Appointment',
    'quickActions.manageSchedule': 'Manage Schedule',
    'quickActions.patientRecords': 'Patient Records',
    'quickActions.updateProfile': 'Update Profile',
    'quickActions.recentActivity': 'Recent Activity',
    'quickActions.selectAction': 'Select an action to get started',
    'quickActions.patientName': 'Patient Name',
    'quickActions.enterPatientName': 'Enter patient name',
    'quickActions.appointmentType': 'Appointment Type',
    'quickActions.consultation': 'Consultation',
    'quickActions.followUp': 'Follow-up',
    'quickActions.emergency': 'Emergency',
    'quickActions.routineCheckup': 'Routine Check-up',
    'quickActions.scheduleAppointment': 'Schedule Appointment',
    'quickActions.todaysAvailability': 'Today\'s Availability',
    'quickActions.manageSlot': 'Manage {time} slot',
    'quickActions.blockLunch': 'Block time for lunch (12:00 PM - 1:00 PM)',
    'quickActions.addEmergencySlot': 'Add emergency slot',
    'quickActions.setOutOfOffice': 'Set out of office',
    'quickActions.emergencyServices': 'Emergency Services',
    'quickActions.poisonControl': 'Poison Control',
    'quickActions.mentalHealthCrisis': 'Mental Health Crisis',
    'quickActions.primaryCare': 'Your Primary Care',
    'quickActions.call': 'Call',
    'quickActions.email': 'Email',
    
    // Appointments
    'appointments.title': 'My Appointments',
    'appointments.description': 'Manage your healthcare appointments',
    'appointments.bookNew': 'Book New Appointment',
    'appointments.searchPlaceholder': 'Search appointments...',
    'appointments.upcoming': 'Upcoming',
    'appointments.past': 'Past',
    'appointments.noUpcoming': 'No upcoming appointments',
    'appointments.noPast': 'No past appointments',
    'appointments.noUpcomingDesc': 'You don\'t have any upcoming appointments scheduled.',
    'appointments.noPastDesc': 'You don\'t have any past appointments to show.',
    'appointments.noMatchingSearch': 'matching your search',
    'appointments.adjustSearch': 'Try adjusting your search terms.',
    'appointments.bookFirst': 'Book Your First Appointment',
    'appointments.confirmed': 'confirmed',
    'appointments.pending': 'pending',
    'appointments.completed': 'completed',
    'appointments.cancelled': 'cancelled',
    'appointments.reschedule': 'Reschedule',
    'appointments.cancel': 'Cancel',
    'appointments.bookAgain': 'Book Again',
    'appointments.review': 'Review',
    'appointments.confirmCancel': 'Are you sure you want to cancel this appointment?',
    'appointments.cancelSuccess': 'Appointment {id} has been cancelled. You will receive a confirmation email.',
    'appointments.rescheduleDesc': 'Reschedule functionality for appointment {id} would open the booking calendar here.',
    'appointments.bookAgainDesc': 'Booking again with {provider}. This would open the appointment booking modal.',
    'appointments.reviewDesc': 'Leave a review for {provider}. This would open a review modal.',
    
    // Account Setup
    'accountSetup.welcome': 'Welcome to MedConnect, {name}!',
    'accountSetup.howToUse': 'How would you like to use our platform?',
    'accountSetup.patient': 'I\'m a Patient',
    'accountSetup.patientDesc': 'Find and book appointments with healthcare providers in your area',
    'accountSetup.provider': 'I\'m a Healthcare Provider',
    'accountSetup.providerDesc': 'Grow your practice with our comprehensive business tools',
    'accountSetup.continueAsPatient': 'Continue as Patient',
    'accountSetup.startBusiness': 'Start Business Account',
    'accountSetup.upgradeNote': 'You can always upgrade to a business account later from your profile settings',
    'accountSetup.setupProfile': 'Set up your provider profile',
    'accountSetup.practiceInfo': 'Tell us about your practice and services',
    'accountSetup.selectSpecialty': 'Select your specialty',
    'accountSetup.practiceLocation': 'Practice Location',
    'accountSetup.cityState': 'City, State',
    'accountSetup.servicesOffered': 'Services Offered',
    'accountSetup.businessAccount': 'Business Account',
    'accountSetup.fullAccess': 'Full access to provider dashboard, appointment management, and analytics',
    'accountSetup.processing': 'Processing...',
    'accountSetup.activateBusiness': 'Activate Business Account',
    
    // Login & Register
    'auth.signInToMedConnect': 'Sign in to MedConnect',
    'auth.createAccount': 'Create your account',
    'auth.dontHaveAccount': 'Don\'t have an account?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.getStartedFree': 'Get started for free',
    'auth.signIn': 'Sign in',
    'auth.emailAddress': 'Email address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.fullName': 'Full name',
    'auth.phoneNumber': 'Phone number',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.createAccountBtn': 'Create account',
    'auth.demoAccounts': 'Demo accounts',
    'auth.demoClient': 'Demo Client',
    'auth.demoProvider': 'Demo Provider',
    'auth.termsOfService': 'Terms of Service',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.agreeToTerms': 'By creating an account, you agree to our',
    'auth.and': 'and',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.passwordsNoMatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 6 characters long',
    'auth.registrationFailed': 'Registration failed. Please try again.',
    
    // Provider Dashboard
    'dashboard.welcomeBack': 'Welcome back, Dr. {name}',
    'dashboard.overview': 'Overview',
    'dashboard.appointments': 'Appointments',
    'dashboard.patients': 'Patients',
    'dashboard.settings': 'Settings',
    'dashboard.totalAppointments': 'Total Appointments',
    'dashboard.activePatients': 'Active Patients',
    'dashboard.monthlyRevenue': 'Monthly Revenue',
    'dashboard.averageRating': 'Average Rating',
    'dashboard.fromLastMonth': 'from last month',
    'dashboard.todaysSchedule': 'Today\'s Schedule',
    'dashboard.addAppointment': 'Add Appointment',
    'dashboard.manageAvailability': 'Manage Availability',
    'dashboard.viewPatientRecords': 'View Patient Records',
    'dashboard.updateProfile': 'Update Profile',
    'dashboard.newAppointmentBooked': 'New appointment booked',
    'dashboard.newReviewReceived': 'New 5-star review received',
    'dashboard.revenueIncreased': 'Monthly revenue increased by 18%',
    'dashboard.hoursAgo': 'hours ago',
    'dashboard.dayAgo': 'day ago',
    'dashboard.daysAgo': 'days ago',
    'dashboard.appointmentManagement': 'Appointment Management',
    'dashboard.appointmentFeatures': 'Comprehensive appointment management features coming soon...',
    'dashboard.patientManagement': 'Patient Management',
    'dashboard.patientFeatures': 'Patient records and communication tools coming soon...',
    'dashboard.accountSettings': 'Account Settings',
    'dashboard.settingsFeatures': 'Profile and practice settings coming soon...',
    
    // Booking
    'booking.bookAppointment': 'Book Appointment',
    'booking.selectDateTime': 'Select date and time for your appointment',
    'booking.selectDate': 'Select Date',
    'booking.selectTime': 'Select Time',
    'booking.selectedDate': 'Selected Date',
    'booking.availableTimes': 'Available Times',
    'booking.noAvailableSlots': 'No available time slots for this date',
    'booking.selectDateFirst': 'Please select a date to view available times',
    'booking.bookingSummary': 'Booking Summary',
    'booking.provider': 'Provider',
    'booking.specialty': 'Specialty',
    'booking.fee': 'Fee',
    'booking.confirmBooking': 'Confirm Booking',
    'booking.booking': 'Booking...',
    'booking.previousMonth': 'Previous month',
    'booking.nextMonth': 'Next month',
    'booking.available': 'Available',
    'booking.unavailable': 'Unavailable',
    'booking.selected': 'Selected',
    'booking.specificConcerns': 'Any specific concerns or symptoms you\'d like to mention...',
    'booking.consultationFee': 'Consultation Fee',
    
    // Language Names
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.arabic': 'العربية',
    'lang.spanish': 'Español',
    'lang.german': 'Deutsch',
    'lang.italian': 'Italiano'
  },
  
  fr: {
    // Navigation
    'nav.welcome': 'Bienvenue',
    'nav.quickActions': 'Actions Rapides',
    'nav.dashboard': 'Tableau de Bord',
    'nav.appointments': 'Rendez-vous',
    'nav.profile': 'Profil',
    'nav.logout': 'Déconnexion',
    'nav.signIn': 'Se Connecter',
    'nav.getStarted': 'Commencer',
    'nav.myAppointments': 'Mes Rendez-vous',
    
    // Home Page
    'home.title': 'Connectez-vous avec les',
    'home.subtitle': 'Professionnels de Santé',
    'home.description': 'La plateforme unifiée qui rassemble patients et professionnels de santé. Prenez rendez-vous, gérez les services et fournissez des soins de qualité.',
    'home.getStartedFree': 'Commencer Gratuitement',
    'home.findProviders': 'Trouver des Praticiens',
    'home.whyChoose': 'Pourquoi Choisir MedConnect?',
    'home.builtFor': 'Conçu pour les patients et les professionnels de santé',
    
    // Features
    'features.forPatients': 'Pour les Patients',
    'features.forProviders': 'Pour les Praticiens',
    'features.secureReliable': 'Sécurisé et Fiable',
    'features.freeForever': 'Gratuit pour toujours',
    'features.easyBooking': 'Prise de rendez-vous facile',
    'features.providerReviews': 'Avis et notes des praticiens',
    'features.professionalDashboard': 'Tableau de bord professionnel',
    'features.appointmentManagement': 'Gestion des rendez-vous',
    'features.revenueTracking': 'Suivi des revenus',
    'features.hipaaCompliant': 'Conforme HIPAA',
    'features.encryption': 'Chiffrement de bout en bout',
    'features.support247': 'Support 24/7',
    
    // Stats
    'stats.activePatients': 'Patients Actifs',
    'stats.healthcareProviders': 'Professionnels de Santé',
    'stats.appointmentsBooked': 'Rendez-vous Réservés',
    'stats.averageRating': 'Note Moyenne',
    
    // CTA
    'cta.transformHealthcare': 'Prêt à Transformer les Soins de Santé?',
    'cta.joinThousands': 'Rejoignez des milliers de patients et de praticiens qui font confiance à MedConnect pour leurs besoins de santé.',
    'cta.startJourney': 'Commencez Votre Parcours',
    
    // Common
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.book': 'Réserver',
    'common.view': 'Voir',
    'common.manage': 'Gérer',
    'common.update': 'Mettre à jour',
    'common.add': 'Ajouter',
    'common.remove': 'Supprimer',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.submit': 'Soumettre',
    'common.reset': 'Réinitialiser',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.back': 'Retour',
    'common.continue': 'Continuer',
    'common.finish': 'Terminer',
    'common.select': 'Sélectionner',
    'common.choose': 'Choisir',
    'common.optional': 'Optionnel',
    'common.required': 'Requis',
    'common.email': 'Email',
    'common.phone': 'Téléphone',
    'common.name': 'Nom',
    'common.address': 'Adresse',
    'common.date': 'Date',
    'common.time': 'Heure',
    'common.notes': 'Notes',
    'common.type': 'Type',
    'common.status': 'Statut',
    'common.actions': 'Actions',
    
    // Providers Page
    'providers.title': 'Trouver des Professionnels de Santé',
    'providers.description': 'Prenez rendez-vous avec des professionnels de santé qualifiés',
    'providers.searchPlaceholder': 'Rechercher des praticiens, spécialités ou lieux...',
    'providers.showing': 'Affichage de',
    'providers.provider': 'praticien',
    'providers.providers': 'praticiens',
    'providers.sortedByDistance': 'triés par distance',
    'providers.locationBasedResults': 'Résultats basés sur la localisation',
    'providers.noProvidersFound': 'Aucun praticien trouvé',
    'providers.adjustCriteria': 'Essayez d\'ajuster vos critères de recherche ou d\'élargir votre rayon de recherche.',
    'providers.expandRadius': 'Élargir le Rayon de Recherche',
    'providers.viewProfile': 'Voir le Profil',
    'providers.bookAppointment': 'Prendre Rendez-vous',
    'providers.nextAvailable': 'Prochaine disponibilité',
    'providers.perConsultation': 'par consultation',
    'providers.services': 'Services',
    'providers.reviews': 'avis',
    
    // Location
    'location.yourLocation': 'Votre Localisation',
    'location.currentLocation': 'Localisation actuelle détectée',
    'location.gps': '(GPS)',
    'location.useCurrentLocation': 'Utiliser la Localisation Actuelle',
    'location.gettingLocation': 'Obtention de la Localisation...',
    'location.enterManually': 'Saisir l\'Adresse Manuellement',
    'location.enterAddress': 'Entrez votre adresse ou ville',
    'location.addressPlaceholder': 'ex: Paris, France ou 123 Rue de la Paix, Ville',
    'location.setLocation': 'Définir la Localisation',
    'location.finding': 'Recherche...',
    'location.privacyNote': 'Les données de localisation ne sont utilisées que pour trouver des professionnels de santé à proximité.',
    'location.maxDistance': 'Distance Maximale',
    'location.miles': 'kilomètres',
    'location.sortBy': 'Trier Par',
    'location.distance': 'Distance',
    'location.rating': 'Note',
    'location.price': 'Prix (Croissant)',
    'location.location': 'Localisation',
    
    // Specialties
    'specialty.allSpecialties': 'Toutes les Spécialités',
    'specialty.generalMedicine': 'Médecine Générale',
    'specialty.cardiology': 'Cardiologie',
    'specialty.dermatology': 'Dermatologie',
    'specialty.pediatrics': 'Pédiatrie',
    'specialty.psychology': 'Psychologie',
    'specialty.dentistry': 'Dentisterie',
    'specialty.physicalTherapy': 'Kinésithérapie',
    'specialty.nutrition': 'Nutrition',
    'specialty.other': 'Autre',
    
    // Profile
    'profile.title': 'Profil',
    'profile.description': 'Gérez les informations de votre compte et vos préférences',
    'profile.personalInfo': 'Informations Personnelles',
    'profile.editProfile': 'Modifier le Profil',
    'profile.fullName': 'Nom Complet',
    'profile.emailAddress': 'Adresse Email',
    'profile.phoneNumber': 'Numéro de Téléphone',
    'profile.location': 'Localisation',
    'profile.medicalSpecialty': 'Spécialité Médicale',
    'profile.professionalBio': 'Biographie Professionnelle',
    'profile.bioPlaceholder': 'Parlez aux patients de votre expérience et de votre approche des soins...',
    'profile.accountStatus': 'Statut du Compte',
    'profile.accountType': 'Type de Compte',
    'profile.memberSince': 'Membre Depuis',
    'profile.subscription': 'Abonnement',
    'profile.active': 'Actif',
    'profile.business': 'Professionnel',
    'profile.personal': 'Personnel',
    'profile.quickActions': 'Actions Rapides',
    'profile.securitySettings': 'Paramètres de Sécurité',
    'profile.notificationPreferences': 'Préférences de Notification',
    'profile.upgradeToBusiness': 'Passer au Professionnel',
    'profile.notProvided': 'Non fourni',
    'profile.noBio': 'Aucune biographie fournie',
    
    // Language Names
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.arabic': 'العربية',
    'lang.spanish': 'Español',
    'lang.german': 'Deutsch',
    'lang.italian': 'Italiano'
  },
  
  ar: {
    // Navigation
    'nav.welcome': 'مرحباً',
    'nav.quickActions': 'الإجراءات السريعة',
    'nav.dashboard': 'لوحة التحكم',
    'nav.appointments': 'المواعيد',
    'nav.profile': 'الملف الشخصي',
    'nav.logout': 'تسجيل الخروج',
    'nav.signIn': 'تسجيل الدخول',
    'nav.getStarted': 'ابدأ الآن',
    'nav.myAppointments': 'مواعيدي',
    
    // Home Page
    'home.title': 'تواصل مع',
    'home.subtitle': 'المختصين في الرعاية الصحية',
    'home.description': 'المنصة الموحدة التي تجمع المرضى ومقدمي الرعاية الصحية. احجز المواعيد، وأدر الخدمات، وقدم رعاية عالية الجودة.',
    'home.getStartedFree': 'ابدأ مجاناً',
    'home.findProviders': 'ابحث عن الأطباء',
    'home.whyChoose': 'لماذا تختار MedConnect؟',
    'home.builtFor': 'مصمم للمرضى ومقدمي الرعاية الصحية',
    
    // Features
    'features.forPatients': 'للمرضى',
    'features.forProviders': 'للأطباء',
    'features.secureReliable': 'آمن وموثوق',
    'features.freeForever': 'مجاني إلى الأبد',
    'features.easyBooking': 'حجز مواعيد سهل',
    'features.providerReviews': 'تقييمات ومراجعات الأطباء',
    'features.professionalDashboard': 'لوحة تحكم مهنية',
    'features.appointmentManagement': 'إدارة المواعيد',
    'features.revenueTracking': 'تتبع الإيرادات',
    'features.hipaaCompliant': 'متوافق مع HIPAA',
    'features.encryption': 'تشفير شامل',
    'features.support247': 'دعم على مدار الساعة',
    
    // Stats
    'stats.activePatients': 'المرضى النشطون',
    'stats.healthcareProviders': 'مقدمو الرعاية الصحية',
    'stats.appointmentsBooked': 'المواعيد المحجوزة',
    'stats.averageRating': 'متوسط التقييم',
    
    // CTA
    'cta.transformHealthcare': 'مستعد لتحويل الرعاية الصحية؟',
    'cta.joinThousands': 'انضم إلى آلاف المرضى ومقدمي الخدمة الذين يثقون في MedConnect لاحتياجاتهم الصحية.',
    'cta.startJourney': 'ابدأ رحلتك',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.book': 'حجز',
    'common.view': 'عرض',
    'common.manage': 'إدارة',
    'common.update': 'تحديث',
    'common.add': 'إضافة',
    'common.remove': 'إزالة',
    'common.confirm': 'تأكيد',
    'common.close': 'إغلاق',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.reset': 'إعادة تعيين',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.back': 'رجوع',
    'common.continue': 'متابعة',
    'common.finish': 'إنهاء',
    'common.select': 'اختيار',
    'common.choose': 'اختر',
    'common.optional': 'اختياري',
    'common.required': 'مطلوب',
    'common.email': 'البريد الإلكتروني',
    'common.phone': 'الهاتف',
    'common.name': 'الاسم',
    'common.address': 'العنوان',
    'common.date': 'التاريخ',
    'common.time': 'الوقت',
    'common.notes': 'ملاحظات',
    'common.type': 'النوع',
    'common.status': 'الحالة',
    'common.actions': 'الإجراءات',
    
    // Language Names
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.arabic': 'العربية',
    'lang.spanish': 'Español',
    'lang.german': 'Deutsch',
    'lang.italian': 'Italiano'
  },
  
  es: {
    // Navigation
    'nav.welcome': 'Bienvenido',
    'nav.quickActions': 'Acciones Rápidas',
    'nav.dashboard': 'Panel de Control',
    'nav.appointments': 'Citas',
    'nav.profile': 'Perfil',
    'nav.logout': 'Cerrar Sesión',
    'nav.signIn': 'Iniciar Sesión',
    'nav.getStarted': 'Comenzar',
    'nav.myAppointments': 'Mis Citas',
    
    // Home Page
    'home.title': 'Conéctate con',
    'home.subtitle': 'Profesionales de la Salud',
    'home.description': 'La plataforma unificada que conecta pacientes y profesionales de la salud. Reserva citas, gestiona servicios y brinda atención de calidad.',
    'home.getStartedFree': 'Comenzar Gratis',
    'home.findProviders': 'Encontrar Médicos',
    'home.whyChoose': '¿Por qué Elegir MedConnect?',
    'home.builtFor': 'Diseñado para pacientes y profesionales de la salud',
    
    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.book': 'Reservar',
    'common.view': 'Ver',
    'common.manage': 'Gestionar',
    'common.update': 'Actualizar',
    'common.add': 'Añadir',
    'common.remove': 'Eliminar',
    'common.confirm': 'Confirmar',
    'common.close': 'Cerrar',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.submit': 'Enviar',
    'common.reset': 'Restablecer',
    
    // Language Names
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.arabic': 'العربية',
    'lang.spanish': 'Español',
    'lang.german': 'Deutsch',
    'lang.italian': 'Italiano'
  },
  
  de: {
    // Navigation
    'nav.welcome': 'Willkommen',
    'nav.quickActions': 'Schnellaktionen',
    'nav.dashboard': 'Dashboard',
    'nav.appointments': 'Termine',
    'nav.profile': 'Profil',
    'nav.logout': 'Abmelden',
    'nav.signIn': 'Anmelden',
    'nav.getStarted': 'Loslegen',
    'nav.myAppointments': 'Meine Termine',
    
    // Home Page
    'home.title': 'Verbinden Sie sich mit',
    'home.subtitle': 'Gesundheitsfachkräften',
    'home.description': 'Die einheitliche Plattform, die Patienten und Gesundheitsdienstleister zusammenbringt. Termine buchen, Services verwalten und qualitativ hochwertige Pflege bieten.',
    'home.getStartedFree': 'Kostenlos Starten',
    'home.findProviders': 'Ärzte Finden',
    'home.whyChoose': 'Warum MedConnect Wählen?',
    'home.builtFor': 'Entwickelt für Patienten und Gesundheitsdienstleister',
    
    // Common
    'common.loading': 'Laden...',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.edit': 'Bearbeiten',
    'common.delete': 'Löschen',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.book': 'Buchen',
    'common.view': 'Ansehen',
    'common.manage': 'Verwalten',
    'common.update': 'Aktualisieren',
    'common.add': 'Hinzufügen',
    'common.remove': 'Entfernen',
    'common.confirm': 'Bestätigen',
    'common.close': 'Schließen',
    'common.next': 'Weiter',
    'common.previous': 'Zurück',
    'common.submit': 'Senden',
    'common.reset': 'Zurücksetzen',
    
    // Language Names
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.arabic': 'العربية',
    'lang.spanish': 'Español',
    'lang.german': 'Deutsch',
    'lang.italian': 'Italiano'
  },
  
  it: {
    // Navigation
    'nav.welcome': 'Benvenuto',
    'nav.quickActions': 'Azioni Rapide',
    'nav.dashboard': 'Dashboard',
    'nav.appointments': 'Appuntamenti',
    'nav.profile': 'Profilo',
    'nav.logout': 'Disconnetti',
    'nav.signIn': 'Accedi',
    'nav.getStarted': 'Inizia',
    'nav.myAppointments': 'I Miei Appuntamenti',
    
    // Home Page
    'home.title': 'Connettiti con i',
    'home.subtitle': 'Professionisti Sanitari',
    'home.description': 'La piattaforma unificata che riunisce pazienti e professionisti sanitari. Prenota appuntamenti, gestisci servizi e fornisci cure di qualità.',
    'home.getStartedFree': 'Inizia Gratis',
    'home.findProviders': 'Trova Medici',
    'home.whyChoose': 'Perché Scegliere MedConnect?',
    'home.builtFor': 'Progettato per pazienti e professionisti sanitari',
    
    // Common
    'common.loading': 'Caricamento...',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.edit': 'Modifica',
    'common.delete': 'Elimina',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.book': 'Prenota',
    'common.view': 'Visualizza',
    'common.manage': 'Gestisci',
    'common.update': 'Aggiorna',
    'common.add': 'Aggiungi',
    'common.remove': 'Rimuovi',
    'common.confirm': 'Conferma',
    'common.close': 'Chiudi',
    'common.next': 'Avanti',
    'common.previous': 'Indietro',
    'common.submit': 'Invia',
    'common.reset': 'Reimposta',
    
    // Language Names
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.arabic': 'العربية',
    'lang.spanish': 'Español',
    'lang.german': 'Deutsch',
    'lang.italian': 'Italiano'
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('medconnect_language');
    if (savedLanguage && translations[savedLanguage]) {
      setCurrentLanguage(savedLanguage);
      document.documentElement.dir = savedLanguage === 'ar' ? 'rtl' : 'ltr';
    }
  }, []);

  const changeLanguage = (languageCode) => {
    if (translations[languageCode]) {
      setCurrentLanguage(languageCode);
      localStorage.setItem('medconnect_language', languageCode);
      document.documentElement.dir = languageCode === 'ar' ? 'rtl' : 'ltr';
    }
  };

  const t = (key, fallback = key) => {
    return translations[currentLanguage]?.[key] || translations.en?.[key] || fallback;
  };

  const availableLanguages = [
    { code: 'en', name: 'English', nativeName: 'English' },
    { code: 'fr', name: 'French', nativeName: 'Français' },
    { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
    { code: 'es', name: 'Spanish', nativeName: 'Español' },
    { code: 'de', name: 'German', nativeName: 'Deutsch' },
    { code: 'it', name: 'Italian', nativeName: 'Italiano' }
  ];

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      changeLanguage,
      t,
      availableLanguages,
      isRTL: currentLanguage === 'ar'
    }}>
      {children}
    </LanguageContext.Provider>
  );
};